export const DAT_VE = 'DAT_VE'
export const DAT_VE_ASYNC = 'DAT_VE_ASYNC'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_IN_ASYNC = 'SIGN_IN_ASYNC'
export const SIGN_UP = 'SIGN_UP'
export const SIGN_UP_ASYNC = 'SIGN_UP_ASYNC'
export const USER_UPDATE_INFO = 'USER_UPDATE_INFO'
export const USER_UPDATE_INFO_ASYNC = 'USER_UPDATE_INFO_ASYNC'